name: Branch Sub Issues
description:
  Creates branch specific sub-issue for each issue based one labels to track
  work getting applied to release branches.
author: OpenDCS

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs: {}
# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
